version: '3'

services:
  cargiantscrape:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    image: jammyboi/cgwebscrape:latest
    volumes:
      - $(PWD)/used_cars.db:/app/used_cars.db
      - $(PWD)credentials.py:/app/credentials.py
