version: '3'

services:
  cargiantscrape:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./credentials.py:/app/credentials.py 
      - ./modules:/app/modules
      - ./used_cars.db:/app/used_cars.db
