version: '3'

services:
  cargiantscrape:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    volumes:
      - ./used_cars.db:/app/used_cars.db
      - ./modules:/app/modules/
      - ./credentials.py:/app/credentials.py
