version: '3'

services:
  cargiantscrape:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./containerfiles:/app
      - ./modules:/app/modules
