version: '3'

services:
  cargiantscrape:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    image: jammyboi/cgwebscrape:linux-arm-v8-latest
    command: [ "python", "test.py" ]
    volumes:
      - type: bind
        source: ./used_cars.db
        target: /app/used_cars.db