name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARM/v8 image (Linux)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:linux-armv8"
          platforms: linux/arm64/v8,linux/amd64
          file: Dockerfile.linux
          build-args: |
            PANDAS_VERSION=1.3.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push ARM/v7 image (Linux)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:linux-armv7"
          platforms: linux/arm/v7,linux/amd64
          file: Dockerfile.linux
          build-args: |
            PANDAS_VERSION=1.3.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Windows 64-bit image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:windows-amd64"
          platforms: windows/amd64
          file: Dockerfile.windows
          build-args: |
            PANDAS_VERSION=1.3.3
          cache-from: type=gha
          cache-to: type=gha,mode=max
