name: Build and Push Docker Image Windows AMD64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Use a Windows-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:latest"  # Update the tag for Windows AMD64
          platforms: windows/amd64  # Set the platform to Windows AMD64
          build-args: |
            PANDAS_VERSION=1.3.3
          cache-from: type=gha
          cache-to: type=gha,mode=max
