name: Build and Push cross platform Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/arm/v7, linux/arm64/v8, linux/arm/v8, linux/amd64]  # Add more platforms as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push ARM/v7 image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:latest"
          platforms: ${{ matrix.platform }}
          build-args: |
            PANDAS_VERSION=1.3.3
          cache-from: type=gha
          cache-to: type=gha,mode=max
