name: Build from source & Push as latest tag
on:
  push: 
    branches: 
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:latest"
          platforms: linux/386,linux/amd64,linux/arm/v6, linux/arm/v7, linux/arm/v8, linux/arm64,linux/ppc64le,linux/s390x
          build-args: |
            PANDAS_VERSION=1.3.3
            DOCKER_BUILDKIT=1
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline