name: Build and Push Docker Image ARM/v8

on:
  push:
    branches:
      - master

jobs:
  build-armv8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ARM/v8 image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "jammyboi/cgwebscrape:armv8"
          platforms: linux/arm64
          build-args: |
            PANDAS_VERSION=1.3.3
          cache-from: type=registry,ref=jammyboi/cgwebscrape:armv8,mode=max
          cache-to: type=registry,ref=jammyboi/cgwebscrape:armv8,mode=max
