
name: "Manual Build and push"
on:
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/386, linux/amd64, linux/arm/v7, linux/arm/v8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        id: cache-layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: layers-${{ matrix.platform }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            layers-${{ matrix.platform}}-

      - name: Build and push image
        id: build-push-image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: "mytempimage-${{ matrix.platform }}"
          platforms: ${{ matrix.platform }}
          cache-from: type=gha, scope=buildcache-${{ matrix.platform}}
          cache-to: type=gha,mode=max, scope=buildcache-${{ matrix.platform}}
