name: "Daily run and send messages via Telegram"
on:

jobs:
  pull-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Select the images from DockerHub here to test
        image_variant:
          - jammyboi/cgwebscrape:linux-amd64-latest
      fail-fast: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: startsWith(matrix.image_variant, 'jammyboi/cgwebscrape:linux-amd64')


      - name: Install jq 
        run: sudo apt-get install -y jq

      - name: Get all platform manifests of Docker Tag
        id: get-platform-manifests
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Replace `library/ubuntu` with your image's repository name
          IMAGE_NAME="${{ matrix.image_variant }}"

          # Fetch the image manifest using Docker's `docker manifest inspect` command
          MANIFEST=$(docker manifest inspect "${IMAGE_NAME}")

          # Extract all available platforms from the manifest
          PLATFORMS=$(echo "${MANIFEST}" | jq -r '.manifests[].platform | select(. != null) | .os + "/" + .architecture')

          # Iterate over platforms and pull the image for each platform
          for PLATFORM in $PLATFORMS; do
            echo docker pull --platform "${PLATFORM}" "${IMAGE_NAME}"
            docker pull --platform "${PLATFORM}" "${IMAGE_NAME}" || true
          done 
      - name: Make Credentials.py
        run: |
         printf "api_token = "${{ secrets.api_token}}""\nchat_id=${{secrets.chat_id}}" > credentials.py"

      - name: Run Tests
        run: |
          docker run --rm ${{ matrix.image_variant }}

