name: "Daily run and send messages via Telegram"
on:
    workflow_dispatch:
    
jobs:
  pull-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Select the images from DockerHub here to test
        image_variant:
          - jammyboi/cgwebscrape:linux-amd64-latest
      fail-fast: false
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker pull image
        run: |
            docker pull "${{ matrix.image_variant }}"

      - name: Make Credentials.py
        run: |
         printf "api_token = "${{ secrets.api_token}}""\nchat_id=${{secrets.chat_id}}" > credentials.py"

      - name: Run Tests
        run: |
          docker run --rm ${{ matrix.image_variant }}

