name: Pull latest and run test
on:
    workflow_run:
        branches: 
            - master
        workflows:
            - "Build from source & Push to DockerHub as individual tags"
        types:
            - completed
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Pull main repo
              uses: actions/checkout@v2

            - name: Create credentials File
              run: |
                uname -m
                touch credentials.py

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              

            - name: Install QEMU emulation
              run: docker run --privileged --rm tonistiigi/binfmt --install all
            
            - name: Pull docker image
              run: |
                uname -m
                docker run --rm -t arm64v8/ubuntu uname -m 
                sudo apt-get install qemu binfmt-support qemu-user-static
                docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                docker run --rm -t arm64v8/ubuntu uname -m 

                
            - name: Stop container
              run: |
                docker compose down 
