name: Pull different images and run test
on:
  workflow_run:
    workflows:
      - "Build from source & Push to DockerHub as individual tags"
    types:
      - completed

jobs:
  pull-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Select the images from DockerHub here to test
        image_variant:
          - jammyboi/cgwebscrape:linux-armv7-latest
          - jammyboi/cgwebscrape:linux-amd64-latest
          - jammyboi/cgwebscrape:linux-arm64-v8-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install QEMU emulation
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Pull docker image
        run: docker pull --all-tags ${{ matrix.image_variant }}

      - name: Run Tests
        run: |
          docker run --rm ${{ matrix.image_variant }} test.py

      - name: Stop container
        run: docker compose down
