name: Run test on "Build from source & Push to DockerHub as individual tags" workflow
on:
    workflow_run:
        branches: 
            - master
        workflows:
            - "Build from source & Push to DockerHub as individual tags"
        types:
            - completed
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Pull main repo
              uses: actions/checkout@v2

            - name: Create credentials File
              run: touch credentials.py        

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              

            - name: Run Docker-in-QEMU
              run: |
                docker run -v /var/run/docker.sock:/var/run/docker.sock --rm tonistiigi/binfmt:latest sh -c "docker pull jammyboi/cgwebscrape:linux-arm-v8-latest && docker-compose -f test-docker-compose.yaml up"

            - name: Stop container
              run: |
                docker compose down 
