name: Pull different images and run test
on:
  workflow_run:
    workflows:
      - "Build from source & Push to DockerHub as individual tags"
    types:
      - completed

jobs:
  pull-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Select the images from DockerHub here to test
        image_variant:
          - jammyboi/cgwebscrape:linux-armv7-latest
          - jammyboi/cgwebscrape:linux-amd64-latest
          - jammyboi/cgwebscrape:linux-arm64-v8-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install jq 
        run: sudo apt-get install -y jq


      - name: Get all platform manifests of Docker Tag
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # Replace `library/ubuntu` with your image's repository name
          IMAGE_NAME="${{ matrix.image_variant }}"

          # Fetch the image manifest using Docker's `docker manifest inspect` command
          MANIFEST=$(docker manifest inspect "${IMAGE_NAME}")

          # Extract all available platforms from the manifest
          PLATFORMS=$(echo "${MANIFEST}" | jq -r '.manifests[].platform | select(. != null) | .os + "/" + .architecture')

          # Iterate over platforms and pull the image for each platform
          for PLATFORM in $PLATFORMS; do
            echo docker pull --platform "${PLATFORM}" "${IMAGE_NAME}"
            docker pull --platform "${PLATFORM}" "${IMAGE_NAME}"
          done || true


      - name: Run Tests
        run: |
          docker run --rm ${{ matrix.image_variant }} test.py

      - name: Stop container
        run: docker compose down
