name: Pull latest and run test
on:
    workflow_run:
        branches: 
            - master
        workflows:
            - "Build from source & Push to DockerHub as individual tags"
        types:
            - completed
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Pull main repo
              uses: actions/checkout@v2

            - name: Create credentials File
              run: touch credentials.py

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
              

            - name: Install QEMU emulation
              run: docker run --privileged --rm tonistiigi/binfmt --install all

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
              
            
            - name: Pull docker image
              run: |
                # sudo apt-get install qemu binfmt-support qemu-user-static
                docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
                docker run --rm jammyboi/cgwebscrape:linux-arm-v8-latest test.py

                
            - name: Stop container
              run: |
                docker compose down 
