name: Pull latest and run test
on:
    workflow_run:
        branches: 
            - master
        types:
            - completed
jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Pull main repo
              uses: actions/checkout@v2
            - name: Create credentials File
              run: touch credentials.py        
            
            - name: Pull docker image
              run: |
                docker pull jammyboi/cgwebscrape:linux-arm-v8-latest
                docker compose -f test-docker-compose.yaml up
            - name: Stop container
              run: |
                docker compose down 
