name: Pull latest and run test
on:
  workflow_run:
    workflows:
      - "Build from source & Push to DockerHub as individual tags"
    types:
      - completed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull main repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install QEMU emulation
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull docker image
        run: |
          docker pull --platform linux/arm/v8 jammyboi/cgwebscrape:linux-arm-v8-latest
          docker run --rm jammyboi/cgwebscrape:linux-arm-v8-latest test.py

      - name: Stop container
        run: |
          docker compose down
